version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: dhikra-postgres
    environment:
      POSTGRES_DB: dhikra_db
      POSTGRES_USER: dhikra_user
      POSTGRES_PASSWORD: dhikra_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dhikra_user -d dhikra_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend FastAPI Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dhikra-backend
    environment:
      - DATABASE_URL=postgresql://dhikra_user:dhikra_password@postgres:5432/dhikra_db
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/firebase-credentials.json:/app/firebase-credentials.json:ro
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend React Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dhikra-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm start

volumes:
  postgres_data: 